version: "2"

run:
    timeout: 5m
    relative-path-mode: gomod
    issues-exit-code: 1
    tests: true
    modules-download-mode: readonly

output:
    formats:
        text:
            print-linter-name: true
            print-issued-lines: true
            colors: true

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    uniq-by-line: true

linters:
    default: standard
    enable:
        - gocritic # Набор продвинутых правил
        - revive # Проверяет стиль кода, оформление, названия
        - gosec # Проверка на уязвимости и небезопасные практики
        - depguard # Запрещает импорт указанных пакетов (например io/ioutil)
        - bodyclose # Проверяет, что закрывается `resp.Body` у HTTP-запросов
        - asciicheck # Предупреждает о не-ASCII символах в коде
        - cyclop # Контролирует цикломатическую сложность функций (Чем больше if, switch, for, &&, || тем выше сложность)
        - dupl # Находит дублированные фрагменты кода
        - unparam # Неиспользуемые параметры функций
        - errorlint # Рекомендует использовать errors.Is / errors.As
        - errname # Проверяет имена переменных/типов ошибок (должны содержать "Err")
        - forbidigo # Запрещает определённые вызовы или конструкции по regex-паттернам
        - contextcheck # Проверяет, что `context.Context` передаётся в методы/функции
        - containedctx # Предупреждает, если `context.Context` сохраняется в структуре
    disable:
        - gocyclo
        - lll

    exclusions:
        generated: strict # Игнорировать сгенерированные файлы (по "// Code generated ... DO NOT EDIT.")
        rules:
            - path: _test\.go
              linters:
                  - cyclop
                  - dupl
                  - gosec
                  - forbidigo

    settings:
        gosec:
            config:
                global:
                    audit: true
                    show-ignored: true
                severity: "medium"
                confidence: "medium"

        cyclop:
            max-complexity: 15 # максимальная сложность функции, вроде 15 норм

        depguard:
            rules:
                main:
                    deny:
                        - pkg: io/ioutil
                          desc: "Использование устаревшего пакета io/ioutil запрещено (замените вызовы на аналоги из пакетов os/io)"

        revive:
            severity: warning

        forbidigo:
            exclude-godoc-examples: true
            analyze-types: true
            forbid:
                - pattern: '^fmt\.Print.*'
                  msg: "Запрещено напрямую использовать fmt.Print* для логирования (используйте структурированный логгер)"
                - pattern: '^time\.Sleep'
                  msg: "Запрещено использовать time.Sleep в продакшен-коде (используйте таймеры/контекст)"
                - pattern: '^http\.DefaultClient'
                  msg: "Не используйте http.DefaultClient (нет таймаутов); создайте *http.Client с таймаутами"

formatters:
    enable:
        - gofumpt
        - gci
    settings:
        gofumpt:
            extra-rules: true
        gci:
            sections:
                - Standard
                - Default
                - Prefix(github.com/SonOfSteveJobs/habr/)
            no-inline-comments: false
