version: "3"

dotenv: [".env"]

vars:
    GOLANGCI_LINT_VERSION: "v2.10.1"
    GCI_VERSION: "v0.13.7"
    GOFUMPT_VERSION: "v0.9.2"
    BUF_VERSION: "v1.65.0"
    GOOSE_VERSION: "v3.24.3"
    OAPI_CODEGEN_VERSION: "v2.5.1"

    BIN_DIR: "{{.ROOT_DIR}}/bin"
    GOLANGCI_LINT: "{{.BIN_DIR}}/golangci-lint"
    GCI: "{{.BIN_DIR}}/gci"
    GOFUMPT: "{{.BIN_DIR}}/gofumpt"
    BUF: "{{.BIN_DIR}}/buf"
    GOOSE: "{{.BIN_DIR}}/goose"
    OAPI_CODEGEN: "{{.BIN_DIR}}/oapi-codegen"

tasks:
    install-formatters:
        desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
        cmds:
            - |
                [ -f {{.GOFUMPT}} ] || {
                  echo 'Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
                  GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
                }
                [ -f {{.GCI}} ] || {
                  echo 'Устанавливаем gci {{.GCI_VERSION}}...'
                  GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
                }
        status:
            - test -x {{.GOFUMPT}}
            - test -x {{.GCI}}

    format:
        desc: "Форматирует весь проект gofumpt + gci"
        deps: [install-formatters]
        cmds:
            - |
                echo "Форматируем через gofumpt..."
                find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
            - |
                echo "Сортируем импорты через gci..."
                find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/SonOfSteveJobs/habr/)" {} +

    install-golangci-lint:
        desc: "Устанавливает golangci-lint в ./bin"
        cmds:
            - |
                [ -f {{.GOLANGCI_LINT}} ] || {
                  mkdir -p {{.BIN_DIR}}
                  echo "Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
                  GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
                }
        status:
            - test -x {{.GOLANGCI_LINT}}

    lint:
        desc: "Запускает golangci-lint"
        deps: [install-golangci-lint]
        cmds:
            - "{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml"

    install-buf:
        desc: "Устанавливает buf в ./bin"
        cmds:
            - |
                [ -f {{.BUF}} ] || {
                  echo "Устанавливаем buf {{.BUF_VERSION}}..."
                  GOBIN={{.BIN_DIR}} go install github.com/bufbuild/buf/cmd/buf@{{.BUF_VERSION}}
                }
        status:
            - test -x {{.BUF}}

    proto-generate:
        desc: "Генерирует Go-код из proto-файлов"
        deps: [install-buf]
        dir: proto
        cmds:
            - "{{.BUF}} generate"

    install-oapi-codegen:
        desc: "Устанавливает oapi-codegen в ./bin"
        cmds:
            - |
                [ -f {{.OAPI_CODEGEN}} ] || {
                  echo "Устанавливаем oapi-codegen {{.OAPI_CODEGEN_VERSION}}..."
                  GOBIN={{.BIN_DIR}} go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@{{.OAPI_CODEGEN_VERSION}}
                }
        status:
            - test -x {{.OAPI_CODEGEN}}

    openapi-generate:
        desc: "Генерирует Go-код из OpenAPI-схемы gateway"
        deps: [install-oapi-codegen]
        cmds:
            - "{{.OAPI_CODEGEN}} -generate chi-server,models,spec -package gatewayv1 -o pkg/gen/gateway/v1/gateway.gen.go api/gateway/v1/gateway.yaml"

    proto-lint:
        desc: "Линтит proto-файлы"
        deps: [install-buf]
        dir: proto
        cmds:
            - "{{.BUF}} lint"

    test:
        desc: "Запускает unit-тесты"
        cmds:
            - go test -race ./services/... ./pkg/... -v

    test-coverage:
        desc: "Запускает unit-тесты с coverage и генерирует HTML-отчёт"
        cmds:
            - go test -race ./services/... ./pkg/... -coverprofile=coverage.out -covermode=atomic
            - go tool cover -html=coverage.out -o coverage.html

    test-integration:
        desc: "Запускает интеграционные тесты (требует Docker)"
        cmds:
            - go test -tags=integration -v -count=1 -timeout=5m ./tests/...

    run-auth:
        desc: "Запускает auth service локально"
        dotenv: ["services/auth/.env"]
        cmds:
            - go run ./services/auth/cmd

    run-notification:
        desc: "Запускает notification service локально"
        dotenv: ["services/notification/.env"]
        cmds:
            - go run ./services/notification/cmd

    run-gateway:
        desc: "Запускает gateway service локально"
        dotenv: ["services/gateway/.env"]
        cmds:
            - go run ./services/gateway/cmd

    run-article:
        desc: "Запускает article service локально"
        dotenv: ["services/article/.env"]
        cmds:
            - go run ./services/article/cmd

    docker-up:
        desc: "Поднимает все сервисы и инфраструктуру"
        cmds:
            - docker compose up --build

    docker-up-infra:
        desc: "Поднимает инфраструктуру. Можно указать конкретные: task docker-up-infra -- postgres-auth redis"
        cmds:
            - docker compose up {{.CLI_ARGS | default "postgres-auth postgres-article postgres-notification redis kafka kafka-init kafka-ui"}}

    docker-down:
        desc: "Останавливает и удаляет контейнеры"
        cmds:
            - docker compose down

    docker-down-volumes:
        desc: "Останавливает контейнеры и удаляет volumes"
        cmds:
            - docker compose down -v

    install-goose:
        desc: "Устанавливает goose в ./bin"
        cmds:
            - |
                [ -f {{.GOOSE}} ] || {
                  echo "Устанавливаем goose {{.GOOSE_VERSION}}..."
                  GOBIN={{.BIN_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}
                }
        status:
            - test -x {{.GOOSE}}

    migrate-auth-up:
        desc: "Применяет миграции auth"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/auth postgres "postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@localhost:${AUTH_DB_PORT}/auth?sslmode=disable" up'

    migrate-auth-down:
        desc: "Откатывает последнюю миграцию auth"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/auth postgres "postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@localhost:${AUTH_DB_PORT}/auth?sslmode=disable" down'

    migrate-auth-status:
        desc: "Показывает статус миграций auth"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/auth postgres "postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@localhost:${AUTH_DB_PORT}/auth?sslmode=disable" status'

    migrate-article-up:
        desc: "Применяет миграции article"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/article postgres "postgres://${ARTICLE_DB_USER}:${ARTICLE_DB_PASSWORD}@localhost:${ARTICLE_DB_PORT}/article?sslmode=disable" up'

    migrate-article-down:
        desc: "Откатывает последнюю миграцию article"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/article postgres "postgres://${ARTICLE_DB_USER}:${ARTICLE_DB_PASSWORD}@localhost:${ARTICLE_DB_PORT}/article?sslmode=disable" down'

    migrate-article-status:
        desc: "Показывает статус миграций article"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/article postgres "postgres://${ARTICLE_DB_USER}:${ARTICLE_DB_PASSWORD}@localhost:${ARTICLE_DB_PORT}/article?sslmode=disable" status'

    migrate-notification-up:
        desc: "Применяет миграции notification"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/notification postgres "postgres://${NOTIFICATION_DB_USER}:${NOTIFICATION_DB_PASSWORD}@localhost:${NOTIFICATION_DB_PORT}/notification?sslmode=disable" up'

    migrate-notification-down:
        desc: "Откатывает последнюю миграцию notification"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/notification postgres "postgres://${NOTIFICATION_DB_USER}:${NOTIFICATION_DB_PASSWORD}@localhost:${NOTIFICATION_DB_PORT}/notification?sslmode=disable" down'

    migrate-notification-status:
        desc: "Показывает статус миграций notification"
        deps: [install-goose]
        cmds:
            - '{{.GOOSE}} -dir migrations/notification postgres "postgres://${NOTIFICATION_DB_USER}:${NOTIFICATION_DB_PASSWORD}@localhost:${NOTIFICATION_DB_PORT}/notification?sslmode=disable" status'
