replicaCount: 1

image:
  repository: ghcr.io/sonofstevejobs/habr-auth
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

migration:
  enabled: true

resources: {}

env: {}
envFromSecret: {}
