apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notification.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: notification
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secretName := .Values.envFromSecret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $key }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
